trigger: none
pool: pkagent
stages:
  - stage: cistage
    jobs:
      - job: publishJob
        steps:
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)/app.py'
            ArtifactName: 'todoapi'
            publishLocation: 'Container'
  - stage: cdstage
    jobs:
      - deployment: tododeploy
        environment: 
         name: tododev
         resourceName: todovm002
         resourceType: virtualMachine   
        strategy:
         runOnce:
          deploy:
            steps:
            - task: DownloadBuildArtifacts@1
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: 'todoapi'
                downloadPath: '/home/sysadmin/todo'
                cleanDestinationFolder: true
            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: 'sudo systemctl restart pytodo.service'
           

